### PR TITLE
Update Dockerfile for Alpine 3.16 & latest client version

### PR DESCRIPTION
**Pull request by nallenscott**
Update Dockerfile.alpine to:
* Alpine Linux 3.16
* Node.js 16 LTS
* Aerospike Node.js client 5.0.1
* Aerospike C client 6.0.2

### CODE REVIEW

**Comment by realmgic** [comment]
Hi @nallenscott - did you run `npm test` with the container you built? it doesn't seem to work for me:
```
/src/node_modules/aerospike # OPTIONS="--host 172.17.0.3" npm test

> aerospike@5.0.1 test
> mocha


Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /src/node_modules/aerospike/lib/binding/node-v93-linux-x64/aerospike.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/src/node_modules/aerospike/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/src/node_modules/aerospike/lib/aerospike.js:19:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/src/node_modules/aerospike/test/aerospike.js:21:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/src/node_modules/aerospike/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/src/node_modules/aerospike/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/src/node_modules/aerospike/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/src/node_modules/aerospike/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/src/node_modules/aerospike/node_modules/mocha/lib/cli/run.js:374:5)
`

**Comment by rpandian-spike** [comment]
C-Client is submodule of nodejs and it shouldn't be built from outside. Please refer README file about how to build nodejs client.

**Comment by nallenscott** [comment]
@realmgic Thanks. Do you mind if I port your changes here? I also have a working example for AWS Lambda that I'll open a new PR for.

**Comment by realmgic** [comment]
Thanks @nallenscott - I think @rpandian-spike already merged my fixes into the master and 4.x branches - along with the fix to the build script I suggested.
I'll be looking out for your other PR because I'm having some issues making the lambda thing to work and would love to see how you did that there.

**Comment by nallenscott** [comment]
@realmgic Awesome. I'll close this PR as a learning experience.

**Pull request closed without merging**
