### PR TITLE
CLIENT-1465: Add support for boolean particle type

### PR DESCRIPTION
**Pull request by jhecking**

### CODE REVIEW

**Comment by bit0r1n** [comment]
What about boolean value in operations (I got error with write)? Did you forgot or it is not supported?

**Comment by jhecking** [comment]
Can you give a sample of what exactly you are trying to do and what error you got?

**Comment by bit0r1n** [comment]
`client.operate(key, [operations.write("bin_name", true)])`
<details>
  <summary>Output</summary>
└ep 16 2021 14:29:47 Aaea?onu (ceia): ERROR(10904) [scalar_operations.cc:84] [add_write_op] - Type error in write operation
└ep 16 2021 14:29:47 Aaea?onu (ceia): ERROR(10904) [operations.cc:64] [operations_from_jsarray] - invalid operation [0] - result: -1
└ep 16 2021 14:29:47 Aaea?onu (ceia): ERROR(10904) [command.cc:84] [ErrorCallback] - Client error in Operate command: Operations array invalid [-2]
</details>

**Comment by jhecking** [comment]
You are right, I missed adding support for boolean values to the `write` operation. I'm tracking this in #433.

**Pull request merged**
