### PR TITLE
connection string functionality

### PR DESCRIPTION
**Pull request by mrbar42**
add support for connection string in common formats

```javascript

var config = {
    hosts: 'aerospike://192.168.0.1:3000,192.168.0.2'
 // hosts: 'as://node1,node2'
 // hosts: '192.168.0.1,node1:3030'
 // hosts: process.env.AEROSPIKE_HOSTS || 'localhost'
  }
```

### CODE REVIEW

**Comment by jhecking** [comment]
@mrbar42, thanks for the PR! Having a standardize way to read the cluster config from an environment variable would be nice. Maybe we can even have the client read from a specific environment variable if no host configuration is provided in the code explicitly.

But is there a specific need for the `aerospike://` protocol prefix? It seems just specifying the host names/ports as in your third example (`192.168.0.1,node1:3030`) would serve the same purpose and would reduce complexity in the parsing logic. I especially don't see the need for supporting two different protocol designators.

**Comment by mrbar42** [comment]
I thought of hard coding an environment variable too, but I didn't know which one to pick. 
I actually think the best one would be AEROSPIKE_STRING. 

Tell me which one is most suitable and i will update the PR

Same for protocol,  currently you can use 'as://'  'aerospike://'  or no protocol prefix at all,
All would work. 

I'm not sure if either format should be the only one. 
Let me know what you think.

**Comment by jhecking** [comment]
Something like `aerospike://10.0.0.1:3000,10.0.0.2:3000` wouldn't be a valid URI as a URI cannot have multiple `host:port` parts. So let's keep it simple and just use a comma separated list of hosts with optional ports, i.e.

    host [ ":" port ] *( "," host [ ":" port ] )

Let's use `AEROSPIKE_HOSTS` as the name for the environment variable.

**Comment by mrbar42** [comment]
I've made the updates.

also updated the docs.

**Comment by jhecking** [comment]
@mrbar42, this looks good now. But can you please update the code to conform to the [JavaScript Standard Style](http://standardjs.com/) that we are following for this project:

````
$ npm test

> aerospike@1.0.56 test /Users/jhecking/aerospike/aerospike-client-nodejs
> standard && mocha

standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:253:1: Trailing spaces not allowed.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:254:65: Strings must use singlequote.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:255:1: Trailing spaces not allowed.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:256:27: Expected '===' and instead saw '=='.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:257:50: Extra semicolon.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:259:1: Trailing spaces not allowed.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:490:26: Missing space before function parentheses.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:491:5: Expected indentation of 2 space characters but found 4.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:492:9: Expected indentation of 6 space characters but found 8.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:492:25: Strings must use singlequote.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:492:71: Extra semicolon.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:495:5: Expected indentation of 2 space characters but found 4.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:497:34: Requires a space after "{".
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:497:45: Requires a space before "}".
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:499:17: Expected indentation of 14 space characters but found 16.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:499:43: Extra semicolon.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:500:17: Expected indentation of 14 space characters but found 16.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:501:21: Expected indentation of 18 space characters but found 20.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:502:21: Expected indentation of 18 space characters but found 20.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:502:27: Missing radix parameter.
  /Users/jhecking/aerospike/aerospike-client-nodejs/lib/aerospike.js:504:15: Extra semicolon.
npm ERR! Test failed.  See above for more details.
````

**Comment by mrbar42** [comment]
Whoops...
my bad - fixed

**Comment by jhecking** [comment]
This was merged in 5a44351. I did a rebase on master before merging so Github doesn't seem to recognize that it has been merged.

**Pull request closed without merging**
